# في دالة _seed_data()، أضف هذه المسائل الجديدة:

{
    "topic": "ibadat",
    "title_ar": "صيام رمضان",
    "title_en": "Ramadan Fasting",
    "title_fr": "Jeûne du Ramadan",
    "title_fa": "روزه رمضان",
    "title_ms": "Puasa Ramadan",
    "title_ur": "رمضان کے روزے",
    "keywords_ar": "صيام,صوم,رمضان,فطر,إفطار,سحور,عشر,ليلة القدر",
    "keywords_en": "fasting,ramadan,iftar,suhoor,qadr",
    "keywords_fr": "jeûne,ramadan,iftar,suhoor,qadr",
    "keywords_fa": "روزه,رمضان,افطار,سحری,قدر",
    "keywords_ms": "puasa,ramadan,iftar,sahur,qadr",
    "keywords_ur": "روزہ,رمضان,افطار,سحری,قدر",
    "ruling_vs_ar": "فرض عين",
    "ruling_s_ar": "صيام رمضان فرض على كل مسلم مكلف",
    "ruling_f_ar": "صيام شهر رمضان فرض عين على كل مسلم بالغ عاقل قادر، وهو أحد أركان الإسلام الخمسة، ويجب على المسلم الامتناع عن الأكل والشرب وسائر المفطرات من الفجر إلى المغرب.",
    "ruling_vs_en": "Individual obligation",
    "ruling_s_en": "Fasting Ramadan is obligatory for every accountable Muslim",
    "ruling_f_en": "Fasting the month of Ramadan is an individual obligation on every adult, sane, capable Muslim, and is one of the five pillars of Islam.",
    "ruling_vs_fr": "Obligation individuelle",
    "ruling_s_fr": "Le jeûne du Ramadan est obligatoire pour tout musulman responsable",
    "ruling_f_fr": "Le jeûne du mois de Ramadan est une obligation individuelle pour tout musulman adulte, sain d'esprit et capable, et est l'un des cinq piliers de l'Islam.",
    "ruling_vs_fa": "فرض عین",
    "ruling_s_fa": "روزه رمضان بر هر مسلمان مکلّف واجب است",
    "ruling_f_fa": "روزه ماه رمضان فرض عین بر هر مسلمان بالغ عاقل توانا است و یکی از ارکان پنجگانه اسلام محسوب می‌شود.",
    "ruling_vs_ms": "Fardu ain",
    "ruling_s_ms": "Puasa Ramadan wajib ke atas setiap Muslim yang mukallaf",
    "ruling_f_ms": "Puasa bulan Ramadan adalah fardu ain ke atas setiap Muslim yang baligh, berakal dan mampu, dan merupakan salah satu rukun Islam yang lima.",
    "ruling_vs_ur": "فرض عین",
    "ruling_s_ur": "رمضان کے روزے ہر مکلف مسلمان پر فرض ہیں",
    "ruling_f_ur": "رمضان المبارک کے روزے ہر مسلمان بالغ عاقل قادر پر فرض عین ہیں، اور یہ اسلام کے پانچ ارکان میں سے ایک ہے۔",
    "rulings_by_madhab_ar": json.dumps({
        "maliki": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين على كل مسلم مكلف، ويجب النية من الليل."},
        "shafii": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين، ويجب تبييت النية لكل يوم."},
        "hanafi": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين، وتجب النية قبل طلوع الفجر."},
        "hanbali": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين، ويجب تبييت النية من الليل."},
        "jafari": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين، ويجب النية من الليل."},
        "ibadi": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم مكلف", "full": "صيام رمضان فرض عين على كل مسلم مكلف."}
    }),
    "rulings_by_madhab_en": "{}",
    "rulings_by_madhab_fr": "{}",
    "rulings_by_madhab_fa": "{}",
    "rulings_by_madhab_ms": "{}",
    "rulings_by_madhab_ur": "{}"
},
{
    "topic": "ibadat",
    "title_ar": "زكاة الفطر",
    "title_en": "Zakat al-Fitr",
    "title_fr": "Zakat al-Fitr",
    "title_fa": "زکات فطره",
    "title_ms": "Zakat Fitrah",
    "title_ur": "زکاة الفطر",
    "keywords_ar": "زكاة,فطر,رمضان,صدقة,طعام,تمر,شعير",
    "keywords_en": "zakat,fitr,ramadan,charity,food,dates,barley",
    "keywords_fr": "zakat,fitr,ramadan,charité,nourriture,dattes,orge",
    "keywords_fa": "زکات,فطره,رمضان,صدقه,غذا,خرما,جو",
    "keywords_ms": "zakat,fitrah,ramadan,sedekah,makanan,kurma,barli",
    "keywords_ur": "زکاة,فطر,رمضان,صدقہ,کھانا,کھجور,جو",
    "ruling_vs_ar": "فرض عين",
    "ruling_s_ar": "زكاة الفطر فرض عين على كل مسلم",
    "ruling_f_ar": "زكاة الفطر فرض عين على كل مسلم يملك قوته يوم العيد، وتجب قبل صلاة العيد، وهي طهرة للصائم من اللغو والرفث.",
    "ruling_vs_en": "Individual obligation",
    "ruling_s_en": "Zakat al-Fitr is obligatory for every Muslim",
    "ruling_f_en": "Zakat al-Fitr is an individual obligation on every Muslim who has enough food for Eid day, and must be given before Eid prayer.",
    "ruling_vs_fr": "Obligation individuelle",
    "ruling_s_fr": "La Zakat al-Fitr est obligatoire pour tout musulman",
    "ruling_f_fr": "La Zakat al-Fitr est une obligation individuelle pour tout musulman qui a assez de nourriture pour le jour de l'Aïd, et doit être donnée avant la prière de l'Aïd.",
    "ruling_vs_fa": "فرض عین",
    "ruling_s_fa": "زکات فطره بر هر مسلمانی واجب است",
    "ruling_f_fa": "زکات فطره بر هر مسلمانی که غذای کافی برای روز عید دارد واجب است و باید قبل از نماز عید پرداخت شود.",
    "ruling_vs_ms": "Fardu ain",
    "ruling_s_ms": "Zakat Fitrah wajib ke atas setiap Muslim",
    "ruling_f_ms": "Zakat Fitrah adalah fardu ain ke atas setiap Muslim yang mempunyai makanan cukup untuk hari raya, dan wajib diberikan sebelum solat hari raya.",
    "ruling_vs_ur": "فرض عین",
    "ruling_s_ur": "زکاة الفطر ہر مسلمان پر فرض ہے",
    "ruling_f_ur": "زکاة الفطر ہر اس مسلمان پر فرض ہے جس کے پاس عید کے دن کا کھانا ہو، اور عید کی نماز سے پہلے ادا کرنی چاہیے۔",
    "rulings_by_madhab_ar": json.dumps({
        "maliki": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم", "full": "زكاة الفطر فرض عين على كل مسلم، وتجب بصاع من طعام."},
        "shafii": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم", "full": "زكاة الفطر فرض عين على كل مسلم، وتجب بصاع من قوت البلد."},
        "hanafi": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم", "full": "زكاة الفطر فرض عين على كل مسلم، وتجب بصاع من تمر أو شعير."},
        "hanbali": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم", "full": "زكاة الفطر فرض عين على كل مسلم، وتجب بصاع من طعام."},
        "jafari": {"very_short": "واجب", "short": "واجب على كل مسلم", "full": "زكاة الفطر واجبة على كل مسلم، وتجب بصاع من طعام."},
        "ibadi": {"very_short": "فرض عين", "short": "فرض عين على كل مسلم", "full": "زكاة الفطر فرض عين على كل مسلم."}
    }),
    "rulings_by_madhab_en": "{}",
    "rulings_by_madhab_fr": "{}",
    "rulings_by_madhab_fa": "{}",
    "rulings_by_madhab_ms": "{}",
    "rulings_by_madhab_ur": "{}"
}
